### ISSUE TITLE
Footer tidak responsive

### ISSUE THREAD

**Issue by aldoxyn** [pt-kompas-media-nusantara/kompas-web-components#2]
Footer tidak responsive di layar Ipad hingga tampilan mobile.

Terlampir screenshotnya:

<img width="928" alt="Ipad" src="https://user-images.githubusercontent.com/53471962/122742138-dafc2700-d2af-11eb-9c17-5f71491f1d9f.png">

**Comment by gajayana** [comment]
ok dicek

**Comment by gajayana** [comment]
@aldoxyn Ini hasil pengecekan di layar tablet (ipad) & mobile (iphone 5) dan masih sesuai harapan. 

<img width="1680" alt="Screen Shot 2021-06-23 at 11 43 29" src="https://user-images.githubusercontent.com/4714334/123037489-f3d41c00-d418-11eb-9a6f-e77dc559bd35.png">
<img width="1680" alt="Screen Shot 2021-06-23 at 11 43 41" src="https://user-images.githubusercontent.com/4714334/123037500-f9316680-d418-11eb-8faa-2a345f58325c.png">

1. boleh tahu peramban apa yang dipakai untuk pengetesan? 
2. apakah di bagian lain halaman ada kontainer yang lebarnya melebihi lebar layar?
